// `.env.ts` is generated by the `npm run env` command
import env from './.env';

// The `window['env']` object is loaded in the `index.html` file
const loadedEnv = window.env || {};

export const environment = {
  production: true,
  version: env.mifos_x.version,
  hash: env.mifos_x.hash,
  // For connecting to server running elsewhere update the tenant identifier
  fineractPlatformTenantId: loadedEnv.fineractPlatformTenantId || 'sandbox',
  fineractPlatformTenantIds: loadedEnv.fineractPlatformTenantIds || 'sandbox',
  // For connecting to others servers running elsewhere update the base API URL
  baseApiUrls: loadedEnv.fineractApiUrls || '',
  baseApiUrl: loadedEnv.fineractApiUrl || 'https://idmb-gateway.nalmart.com/core',
  allowServerSwitch: loadedEnv.allowServerSwitch || 'true',
  apiProvider: loadedEnv.apiProvider || '/api',
  apiVersion: loadedEnv.apiVersion || '/v1',
  serverUrl: '',
  oauth: {
    enabled: loadedEnv.oauthServerEnabled || false, // For connecting to IDM Neo using OAuth2 Authentication change the value to true
    serverUrl: loadedEnv.oauthServerUrl || '',
    appId: loadedEnv.oauthAppId || ''
  },
  /** Feature flag for Remember Me functionality */
  enableRememberMe: false,
  warningDialog: {
    title: 'Warning',
    content:
      'This system is for authorized use only. Unauthorized access will result in possible legal action. By accessing this system, you acknowledge that you are authorized to do so and that all data stored and processed here is confidential.',
    buttonText: 'Close'
  },
  defaultLanguage: loadedEnv.defaultLanguage || 'en-US',
  supportedLanguages:
    loadedEnv.supportedLanguages || 'cs-CS,de-DE,en-US,es-MX,fr-FR,it-IT,ko-KO,lt-LT,lv-LV,ne-NE,pt-PT,sw-SW',
  preloadClients: loadedEnv.preloadClients || true,

  defaultCharDelimiter: loadedEnv.defaultCharDelimiter || ',',

  displayBackEndInfo: loadedEnv.displayBackEndInfo || 'false',
  displayTenantSelector: loadedEnv.displayTenantSelector || 'false',
  // Time in seconds, default 60 seconds
  waitTimeForNotifications: loadedEnv.waitTimeForNotifications || 60,
  // Time in seconds, default 30 seconds
  waitTimeForCOBCatchUp: loadedEnv.waitTimeForCOBCatchUp || 30,
  session: {
    timeout: {
      idleTimeout: loadedEnv.sessionIdleTimeout || 300000 // 5 minutes
    }
  },
  httpCacheEnabled: loadedEnv.httpCacheEnabled || false,

  vNextApiUrl: window.env.vNextApiUrl || 'https://apis.mifos.community',
  vNextApiProvider: window.env.vNextApiProvider || '/vnext1',
  vNextApiVersion: window.env.vNextApiVersion || '/v1.0',
  interbankTransfers: window.env.interbankTransfers || true,

  minPasswordLength: loadedEnv.minPasswordLength || 8,

  OIDC: {
    oidcServerEnabled: window.env.oidcServerEnabled || false,
    oidcBaseUrl: window.env.oidcBaseUrl || '',
    oidcClientId: window.env.oidcClientId || '',
    oidcApiUrl: window.env.oidcApiUrl || '',
    oidcFrontUrl: window.env.oidcFrontUrl || ''
  }
};

// Server URL
environment.serverUrl = `${environment.baseApiUrl}${environment.apiProvider}${environment.apiVersion}`;
